
@startuml DIP

class EncodingModule {
    + encodeWithFiles(): void 
    + encodeBasedOnNetworkAndDatabase(): void 
}

class MyDatabase {
    -  static _data : Map<Integer, String> 
    -  static _count : int  = 0
    + write(String inputString): int

}

class EncodingModuleClient {
    + main(String[] args) : void
}


EncodingModule -> MyDatabase
EncodingModuleClient -> EncodingModule

